"""add_notification_relations_and_reminders

Revision ID: 2747b6863cf8
Revises: 7dfce266f872
Create Date: 2026-09-02 17:25:24.603020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2747b6863cf8'
down_revision: Union[str, None] = '7dfce266f872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('related_case_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('related_hearing_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notifications_related_case_id'), 'notifications', ['related_case_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_hearing_id'), 'notifications', ['related_hearing_id'], unique=False)
    op.create_index(op.f('ix_notifications_reminder_at'), 'notifications', ['reminder_at'], unique=False)
    op.create_foreign_key(None, 'notifications', 'cases', ['related_case_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'hearings', ['related_hearing_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_reminder_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_hearing_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_case_id'), table_name='notifications')
    op.drop_column('notifications', 'reminder_at')
    op.drop_column('notifications', 'related_hearing_id')
    op.drop_column('notifications', 'related_case_id')
    # ### end Alembic commands ###
